name: trigger from workflow dispatch

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Git tag to use for building docker image'
        required: true
        type: string

jobs:
  build-publish-docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the tag
        uses: actions/checkout@v3
      - name: basic shell ops
        run: |
          echo "Tags: ${{ inputs.tags }}"
          echo "Tag name from github.ref_name: ${{ github.ref_name }}"
          ls -ltrh
          cd mlops-sample-demo/service
        env:
          GIT_TAG: ${{ inputs.tags }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: azure docker log-in
        uses: azure/docker-login@v1
        with:
          login-server: sriharshademo.azurecr.io # default: index.docker.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: docker build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: sriharshademo.azurecr.io/telco-service:${{ github.ref_name }}
